### Get all cities
GET http://localhost:8080/cities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiaWQiOjQsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJmaXJzdE5hbWUiOiJUZXN0IiwibGFzdE5hbWUiOiJVc2VyIiwiaWF0IjoxNzQ3NDA3MDk5LCJleHAiOjE3NDc0MTA2OTl9.ZJgfN7QHG4d-1L59LWxwB1b82oQX6CZSTo7ZOZSQChM

### Get existing city by id
GET http://localhost:8080/cities/3
Content-Type: application/json

### Get not-existing city by id
GET http://localhost:8080/cities/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiaWQiOjQsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJmaXJzdE5hbWUiOiJUZXN0IiwibGFzdE5hbWUiOiJVc2VyIiwiaWF0IjoxNzQ3NDA3MDk5LCJleHAiOjE3NDc0MTA2OTl9.ZJgfN7QHG4d-1L59LWxwB1b82oQX6CZSTo7ZOZSQChM

### Create new city
POST http://localhost:8080/cities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiaWQiOjQsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJmaXJzdE5hbWUiOiJUZXN0IiwibGFzdE5hbWUiOiJVc2VyIiwiaWF0IjoxNzQ3NDA3MDk5LCJleHAiOjE3NDc0MTA2OTl9.ZJgfN7QHG4d-1L59LWxwB1b82oQX6CZSTo7ZOZSQChM

{
  "name": "Brno"
}

### Create new invalid city
POST http://localhost:8080/cities
Content-Type: application/json

{
  "navvme": "Brno"
}

### Create new duplicated city
POST http://localhost:8080/cities
Content-Type: application/json

{
  "name": "Brno"
}

### Update existing city
PUT http://localhost:8080/cities/3
Content-Type: application/json

{
  "name": "Prague"
}

### Update invalid city
PUT http://localhost:8080/cities/2
Content-Type: application/json

{
  "navvme": "Brno"
}

### Update non-existing city
PUT http://localhost:8080/cities/20
Content-Type: application/json

{
  "name": "Prague"
}

### Delete existing city
DELETE http://localhost:8080/cities/3

### Delete non-existing city
DELETE http://localhost:8080/cities/29
